import { StyleSheet } from 'aphrodite/no-important';
import colors, { offsetColor, makeTransparent } from '@lib/colors';

export const styles = StyleSheet.create({
  detailsTitle: {
    display: 'flex',
    flexDirection: 'row',
    flex: '0',
    alignItems: 'center',
    paddingRight: 6,
    backgroundColor: makeTransparent(colors.cyan, 0.1),
  },
  detailsTitleText: {
    margin: '8px',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    flex: '1 1 auto',
    minWidth: '0',
    textAlign: 'center',
    fontSize: '115%',
  },
  detailsHeader: {
    position: 'static',
    flex: '1 1 auto',
    padding: '2px 4px',
  },
  detailsWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
    border: `1px solid ${colors.cyan}`,
    backgroundColor: makeTransparent(colors.cyan, 0.1),
    borderRadius: 4,
    margin: 8,
    boxShadow: `0px 0px 8px ${colors.shadow}`,
  },
  detailsJson: {
    position: 'relative',
    fontSize: 11,
    textAlign: 'left',
    overflow: 'auto',
    borderRadius: 4,
    wordBreak: 'break-all',
    padding: 8,
    maxWidth: '100%',
    flex: 1,
    background: offsetColor(colors.background, 0.1),
  },
  detailPaneContainer: {
    position: 'relative',
    flex: 1,
    display: 'flex',
    overflow: 'hidden',
    background: offsetColor(colors.background, 0.1),
    flexDirection: 'column',
    overflowY: 'auto',
    wordBreak: 'break-all',
  },
  detailPaneColumn: {
    padding: 8,
    ':nth-child(1n) > *': {
      marginTop: 12,
      paddingTop: 12,
      borderTop: `1px dashed ${colors.cyan}`,
    },
    ':nth-child(1n) > :first-child': {
      marginTop: 0,
      paddingTop: 0,
      borderTop: 'none',
    },
  },
  detailsSearchToolbar: {
    backgroundColor: offsetColor(colors.toolbarBackground, 0.25),
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 4,
    borderRadius: 4,
    border: `1px dashed ${colors.foreground}`,
  },
  detailsSearchInput: {
    boxShadow: 'none',
  },
});
