MODULES_PATH = "../../node_modules"
RN_PATH = '../../node_modules/react-native'
ENABLE_HERMES = false
HERMES_PREPROCESSOR_FLAG = ENABLE_HERMES ? "RCT_USE_HERMES=1" : "RCT_USE_HERMES=0"

platform :ios, '12.4'
use_frameworks!
inhibit_all_warnings!
install! 'cocoapods',
         generate_multiple_pod_projects: false, # must be disable for the post_install hook to work properly
         lock_pod_sources: false, # to speed up installation time
         :deterministic_uuids => false

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require_relative "#{RN_PATH}/scripts/react_native_pods"
require_relative "#{MODULES_PATH}/@react-native-community/cli-platform-ios/native_modules"

def thirdparty_pods
  pod 'Starscream', '~> 3.1.0'
  pod 'CocoaAsyncSocket', '~> 7.6.3'
  pod 'Flipper-PeerTalk', '~> 0.0.4'
end

workspace 'PiggyKit'

target 'PiggyKit' do
  project './PiggyKit'
  use_react_native!(
    :path => RN_PATH,
    :hermes_enabled => ENABLE_HERMES,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  thirdparty_pods
  target 'PiggyKitTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  react_native_post_install(installer, :mac_catalyst_enabled => false)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', HERMES_PREPROCESSOR_FLAG]
    end
  end
end
