MODULES_PATH = "../../node_modules"
RN_PATH = '../../node_modules/react-native'

platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require_relative "#{RN_PATH}/scripts/react_native_pods"
require_relative "#{MODULES_PATH}/@react-native-community/cli-platform-ios/native_modules"

def thirdparty_pods
  pod 'Starscream', '~> 3.1.0'
  pod 'CocoaAsyncSocket', '~> 7.6.3'
  pod 'Flipper-PeerTalk', '~> 0.0.4'
end

workspace 'PiggyKit'

target 'PiggyKit' do
  project './PiggyKit'
  use_react_native!(:path => RN_PATH)
  thirdparty_pods
  target 'PiggyKitTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
