platform :osx, '10.14'
#use_frameworks!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'forwarder' do
  project 'forwarder.xcodeproj'
  pod 'CocoaAsyncSocket',     '~> 7.6.3'
  pod 'PeerTalk',             :git => 'https://github.com/rsms/peertalk.git'
end
